[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"

aws-config = "1.6"
aws-sdk-dynamodb = "1.69"
lambda_runtime = "0.13.0"

tokio = { version = "1", features = ["full"] }